#
---
paths:
#  dir_tmp_base_path: '/Library/WebServer/Documents/tmp'
  dir_tmp_base_path: '/Library/WebServer/Documents/Sites/progenetix/tmp'
  web_tmp_base_path: '/tmp'

cgi:
  google_tid: UA-572981-2
  google_dt: Progenetix cancer genome profiling resource

map_params:

## MapBox tiles (for-pay beyond a certain nr. of access per month)
# tiles:  = 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=...'
# attribution: 'Imagery &copy; <a href="https://www.mapbox.com/">Mapbox</a>'
# extra_JS: 'id: "mapbox.streets",'

  plottype: map
  plotid: map
  canvas_w_px: 794
  canvas_h_px: 480
  bubble_stroke_color: '#dd6633'
  bubble_stroke_weight: 1
  bubble_fill_color: '#cc9966'
  bubble_opacity: 0.4
  tiles_source: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
  attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
  extra_JS: ""
  marker_type: 'circle'
  marker_scale: 2
  latitude: 10.0
  longitude: 35.0
  zoom: 2
  zoom_min: 2
  zoom_max: 10
  head: >-
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css" integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ==" crossorigin="" />

