#
---
path_loc: ""
path_web: ""
path_arraydata: ""
skip: 0
limit: 2000
chr2plot: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]
genome: 'GRCh38'
plotid: 'genomeplot'
group_by: 'NCIT'
plotregions: []
markers: []
labels: []
binning: 1000000
bin_match_min: 0.0001
title: ''
subtitle: ''
title_left: ''
text_bottom_left: ""
text_bottom_right: "CC-BY progenetix.org 2020-2022"
min_group_no: 2
text_labels_left_max_letters: 40
text_title_max_letters: 100

# array
cna_gain_threshold: 0.15
cna_loss_threshold: -0.15
segbaseline: 0
probebaseline: 0
plot_adjust_baseline: 0
segment_probecount_min: 2
format_inputfiles: 'pgxseg'
simulated_probes: 'n'
reverse: 'n'
factor_probedots: 1

# sizes
size_plotmargin_px: 25
size_plotmargin_top_px: 25
size_plotmargin_bottom_px: 25
size_title_left_w_px: 0
size_text_px: 9
size_text_title_px: 14
size_text_subtitle_px: 12
size_text_lab_px: 8
size_text_title_left_px: 8
size_plotarea_h_px: 100
size_strip_h_px: 7
size_plotarea_padding: 3
size_plotimage_w_px: 1024
size_plotimage_h_px: 480
size_fracbarea_h_px: 100
size_label_y_w_px: 25
size_label_right_px: 0
size_chromosome_w_px: 12
size_chromosome_padding_px: 3
size_samplestrip_w_px: 10
size_frequencystrip_w_px: 14
size_matrixline_w_px: 14
size_segments_stroke_px: 4
size_centerline_stroke_px: 1
size_clustertree_w_px: 50

# colors
color_plotarea_hex: '#f3f9ff'
color_plotbackground_hex: '#ffffff'
color_plotgrid_hex: '#c0e3ee'
color_text_hex: '#000000'
color_label_y_hex: '#666666'
color_label_bottom_hex: '#999999'
color_var_break_hex: '#EE00DD'
color_var_break_rgb: '238,0,221'
color_var_dup_hex: '#FFC633'
color_var_dup_rgb: '255,198,51'
color_var_del_hex: '#33A0FF'
color_var_del_rgb: '51,160,255'
color_var_amp_hex: '#FF6600'
color_var_amp_rgb: '255,102,0'
color_var_homoloss_hex: '#0033CC'
color_var_homoloss_rgb: '0,51,204'
color_connection_opacity: 0.2

colorschema: orangeblue

local_overrides:
  - 'cna_gain_threshold'
  - 'cna_loss_threshold'
  - 'segment_probecount_min'
  - 'value_plot_y_max'

# values
value_plot_y_max: 100
label_y_m: [-75,-50,-25,0,25,50,75]
plot_unit_y: ""
plottype_values:
  array:
    value_plot_y_max: 3.2
    label_y_m: [-3,-2.5,-2,-1.5,-1,-0.5,0,0.5,1,1.5,2,2.5,3]
    plot_unit_y: ""
  samplestrip:
    label_y_m: []
    plot_unit_y: ""
    size_text_px: 7
    size_plotarea_padding: 1
    size_plotmargin_px: 0
    size_plotmargin_top_px: 0
    size_plotmargin_bottom_px: 0
    size_chromosome_w_px: 0
  frequencystrip:
    label_y_m: []
    plot_unit_y: ""
    size_text_px: 7
    size_plotarea_padding: 1
    size_plotmargin_px: 0
    size_plotmargin_top_px: 0
    size_plotmargin_bottom_px: 0
    size_chromosome_w_px: 0
  multifrequencystrip:
    label_y_m: []
    plot_unit_y: ""
    size_text_px: 10
    size_text_title_left_px: 8
    size_strip_h_px: 20
    size_plotarea_h_px: 0
    title_left_rotation: 0
    size_title_left_w_px: 120
    size_label_right_px: 5
  multistrip:
    label_y_m: []
    plot_unit_y: ""
    size_text_title_left_px: 8
    size_strip_h_px: 10
    size_plotarea_h_px: 0
    title_left_rotation: 0
    size_title_left_w_px: 120
    size_label_right_px: 5
  histogram:
    value_plot_y_max: 100
    label_y_m: [-75,-50,-25,0,25,50,75]
    plot_unit_y: "%"
  multihistogram:
    value_plot_y_max: 100
    label_y_m: [-75,-50,-25,0,25,50,75]
    plot_unit_y: "%"
    size_title_left_w_px: 150
    size_text_title_left_px: 8
    title_left_rotation: 0
    size_strip_h_px: 20
    size_plotarea_h_px: 120
    size_label_right_px: 5
  ideogram:
    value_plot_y_max: 100
    label_y_m: [-75,-50,-25,0,25,50,75]
    plot_unit_y: "%"
  map:
    size_plotimage_w_px: 794
    size_plotimage_h_px: 480

# directives
do_label_y: y
plottype: histogram
titlepos: top
title_left_rotation: none
do_chromosomes_proportional: n
svg_embed: 0

colorschemas:
 orangeblue:
  color_var_dup_hex: '#FFC633'
  color_var_dup_rgb: '255,198,51'
  color_var_del_hex: '#33A0FF'
  color_var_del_rgb: '51,160,255'
  color_var_amp_hex: '#FF6600'
  color_var_amp_rgb: '255,102,0'
  color_var_homoloss_hex: '#0033CC'
  color_var_homoloss_rgb: '0,51,204'
 redgreen:
  color_var_dup_hex: '#EE4500'
  color_var_dup_rgb: '238,69,0'
  color_var_del_hex: '#09F911'
  color_var_del_rgb: '9,249,17'
  color_var_amp_hex: '#CD0000'
  color_var_amp_rgb: '205,0,0'
  color_var_homoloss_hex: '#008B00'
  color_var_homoloss_rgb: '0,139,0'
 greenred:
  color_var_del_hex: '#EE4500'
  color_var_del_rgb: '238,69,0'
  color_var_dup_hex: '#09F911'
  color_var_dup_rgb: '9,249,17'
  color_var_amp_hex: '#008B00'
  color_var_amp_rgb: '0,139,0'
  color_var_homoloss_hex: '#CD0000'
  color_var_homoloss_rgb: '205,0,0'
 bluered:
  color_var_dup_hex: '#33A0FF'
  color_var_dup_rgb: '51,160,255'
  color_var_del_hex: '#EE4500'
  color_var_del_rgb: '238,69,0'
  color_var_amp_hex: '#0033CC'
  color_var_amp_rgb: '0,51,204'
  color_var_homoloss_hex: '#CD0000'
  color_var_homoloss_rgb: '205,0,0'
  
# markers
marker_opacity: 0.4
marker_label_opacity: 0.3
marker_text_px: 9
  
# clustering
cluster_distance_metric: e
cluster_linkage_method: m

########
# maps #
########

# Wikimedia/OpenStreetMap tiles
map_attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery &copy; <a href="https://maps.wikimedia.org/">Wikimedia</a>'
# map_tiles: 'https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png'
map_tiles: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
map_extra_JS: ""

## MapBox tiles (for-pay beyond a certain nr. of access per month)
# map_tiles:  = 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=...'
# map_attribution: 'Imagery &copy; <a href="https://www.mapbox.com/">Mapbox</a>'
# map_extra_JS: 'id: "mapbox.streets",'

map_head: |
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css" integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA==" crossorigin="" />
map_marker_type: 'circle'
map_marker_scale: 2
map_latitude: 10.0
map_longitude: 35.0
map_zoom: 2
map_zoom_min: 2
map_zoom_max: 10
map_bubble_fill_color: '#cc9966'
map_bubble_opacity: 0.4
map_bubble_stroke_color: '#dd6633'
map_bubble_stroke_weight: 1


